export enum PACT_ANNOTATIONS {
    PACT = 'pact',
    PACT_AXIOS = 'pact-axios',
    PACT_DESCRIPTION = 'pact-description',
    PACT_METHOD = 'pact-method',
    PACT_RESPONSE_STATUS = 'pact-response-status',
    PACT_PATH = 'pact-path',
    PACT_MATCHER = 'pact-matcher',
    PACT_EXAMPLE = 'pact-example',
    PACT_QUERY = 'pact-query',
    PACT_REQUEST_BODY = 'pact-request-body',
    PACT_RESPONSE_BODY = 'pact-response-body',
    PACT_REQUEST_HEADER = 'pact-request-header',
    PACT_RESPONSE_HEADER = 'pact-response-header',
}
